language: node_js
node_js:
  - lts/carbon
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
cache: npm
install:
  - npm install
  - npm install -g codecov
script:
  - npm run check-all
  - codecov
deploy:
  - provider: script
    script: ./scripts/aws-deploy.sh
    skip_cleanup: true
    on:
      branch: master
      tags: true
