language: node_js
node_js:
  - lts/carbon
env:
  global:
    - PATH=$HOME/.local/bin:$PATH
before_install:
  - pip install --user awscli
cache: npm
script:
  - npm run check-all
  - npm run build
  - ./scripts/aws-deploy.sh